name: "Build and Deploy to Production"
on:
  push:
    tags:
      - "v*"
jobs:
  docker:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        -
      - name: Docker login
        run: echo ${{ secrets.PAT }} | docker login ghcr.io --username yomanz --password-stdin

      - name: Docker build
        run: docker build -t ghcr.io/widgetbot-io/gohook:${GITHUB_REF#refs/tags/} .

      - name: Docker push tag latest
        run: docker push ghcr.io/widgetbot-io/gohook:${GITHUB_REF#refs/tags/}
  kubernetes-deploy:
    name: Kubernetes deploy
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Use actions/checkout@v2
        uses: actions/checkout@v2

      - name: Kubernetes install
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /bin/kubectl

      - name: Kubernetes setup
        run: |
          mkdir ~/.kube
          echo "${{ secrets.KUBE_CLUSTER_CONFIG }}" > ~/.kube/config

      - name: Kubernetes update image
        run: kubectl set image deployment/gohook gohook=ghcr.io/widgetbot-io/gohook:${GITHUB_REF#refs/tags/}

      - name: Kubernetes verify
        run: kubectl rollout status deployment/gohook

      - name: Kubernetes rollback
        if: failure()
        run: kubectl rollout undo deployment/gohook